// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
  urlSearchParamsBodySerializer,
  formDataBodySerializer,
} from "@hey-api/client-axios";
import type {
  AuthJwtLoginData,
  AuthJwtLoginError,
  AuthJwtLoginResponse,
  AuthJwtLogoutError,
  AuthJwtLogoutResponse,
  RegisterRegisterData,
  RegisterRegisterError,
  RegisterRegisterResponse,
  ResetForgotPasswordData,
  ResetForgotPasswordError,
  ResetForgotPasswordResponse,
  ResetResetPasswordData,
  ResetResetPasswordError,
  ResetResetPasswordResponse,
  VerifyRequestTokenData,
  VerifyRequestTokenError,
  VerifyRequestTokenResponse,
  VerifyVerifyData,
  VerifyVerifyError,
  VerifyVerifyResponse,
  UsersCurrentUserError,
  UsersCurrentUserResponse,
  UsersPatchCurrentUserData,
  UsersPatchCurrentUserError,
  UsersPatchCurrentUserResponse,
  UsersUserData,
  UsersUserError,
  UsersUserResponse,
  UsersPatchUserData,
  UsersPatchUserError,
  UsersPatchUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserError,
  UsersDeleteUserResponse,
  ReadItemError,
  ReadItemResponse,
  CreateItemData,
  CreateItemError,
  CreateItemResponse,
  DeleteItemData,
  DeleteItemError,
  DeleteItemResponse,
  IndexDocumentsData,
  IndexDocumentsError,
  IndexDocumentsResponse,
  GetProgressStreamData,
  GetProgressStreamError,
  GetProgressStreamResponse,
  GetProgressStatusData,
  GetProgressStatusError,
  GetProgressStatusResponse,
  ChatWithImagesData,
  ChatWithImagesError,
  ChatWithImagesResponse,
  SearchDocumentsData,
  SearchDocumentsError,
  SearchDocumentsResponse,
  GetCollectionInfoError,
  GetCollectionInfoResponse,
  ClearCollectionError,
  ClearCollectionResponse,
  GetSearchImageData,
  GetSearchImageError,
  GetSearchImageResponse,
  HealthCheckError,
  HealthCheckResponse,
} from "./types.gen";

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<AuthJwtLoginData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLoginResponse,
    AuthJwtLoginError,
    ThrowOnError
  >({
    ...options,
    ...urlSearchParamsBodySerializer,
    headers: {
      "Content-Type": "application/x-www-form-urlencoded",
      ...options?.headers,
    },
    url: "/auth/jwt/login",
  });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    AuthJwtLogoutResponse,
    AuthJwtLogoutError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/jwt/logout",
  });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<RegisterRegisterData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    RegisterRegisterResponse,
    RegisterRegisterError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/register",
  });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetForgotPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetForgotPasswordResponse,
    ResetForgotPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/forgot-password",
  });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ResetResetPasswordData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ResetResetPasswordResponse,
    ResetResetPasswordError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/reset-password",
  });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyRequestTokenData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyRequestTokenResponse,
    VerifyRequestTokenError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/request-verify-token",
  });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<VerifyVerifyData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    VerifyVerifyResponse,
    VerifyVerifyError,
    ThrowOnError
  >({
    ...options,
    url: "/auth/verify",
  });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersCurrentUserResponse,
    UsersCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchCurrentUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchCurrentUserResponse,
    UsersPatchCurrentUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/me",
  });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    UsersUserResponse,
    UsersUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersPatchUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).patch<
    UsersPatchUserResponse,
    UsersPatchUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<UsersDeleteUserData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    UsersDeleteUserResponse,
    UsersDeleteUserError,
    ThrowOnError
  >({
    ...options,
    url: "/users/{id}",
  });
};

/**
 * Read Item
 */
export const readItem = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    ReadItemResponse,
    ReadItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Create Item
 */
export const createItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<CreateItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    CreateItemResponse,
    CreateItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/",
  });
};

/**
 * Delete Item
 */
export const deleteItem = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<DeleteItemData, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    DeleteItemResponse,
    DeleteItemError,
    ThrowOnError
  >({
    ...options,
    url: "/items/{item_id}",
  });
};

/**
 * Index Documents
 * Start document indexing with progress tracking
 */
export const indexDocuments = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<IndexDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    IndexDocumentsResponse,
    IndexDocumentsError,
    ThrowOnError
  >({
    ...options,
    ...formDataBodySerializer,
    headers: {
      "Content-Type": null,
      ...options?.headers,
    },
    url: "/colpali/index",
  });
};

/**
 * Get Progress Stream
 * Get real-time progress updates via Server-Sent Events
 */
export const getProgressStream = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetProgressStreamData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetProgressStreamResponse,
    GetProgressStreamError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/progress/{task_id}",
  });
};

/**
 * Get Progress Status
 * Get current progress status
 */
export const getProgressStatus = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetProgressStatusData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetProgressStatusResponse,
    GetProgressStatusError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/progress/{task_id}/status",
  });
};

/**
 * Chat With Images
 * Chat with specific images using streaming response
 */
export const chatWithImages = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<ChatWithImagesData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    ChatWithImagesResponse,
    ChatWithImagesError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/chat",
  });
};

/**
 * Search Documents
 * Search indexed documents
 */
export const searchDocuments = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<SearchDocumentsData, ThrowOnError>,
) => {
  return (options?.client ?? client).post<
    SearchDocumentsResponse,
    SearchDocumentsError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/search",
  });
};

/**
 * Get Collection Info
 * Get information about the current document collection
 */
export const getCollectionInfo = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetCollectionInfoResponse,
    GetCollectionInfoError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/info",
  });
};

/**
 * Clear Collection
 * Clear all indexed documents
 */
export const clearCollection = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).delete<
    ClearCollectionResponse,
    ClearCollectionError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/clear",
  });
};

/**
 * Get Search Image
 * Get search result image by ID
 */
export const getSearchImage = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetSearchImageData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetSearchImageResponse,
    GetSearchImageError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/image/{image_id}",
  });
};

/**
 * Health Check
 * Health check endpoint
 */
export const healthCheck = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    HealthCheckResponse,
    HealthCheckError,
    ThrowOnError
  >({
    ...options,
    url: "/colpali/health",
  });
};
